/** @type {import('./model.js').Vendor[]} */
export const vendors = [
  { id: 'ven-1', name: 'Stomana Steel Trade', category: 'Raw materials', status: 'preferred' },
  { id: 'ven-2', name: 'EuroPack Supplies', category: 'Consumables', status: 'active' },
  // Suppliers imported from the «Доставчици» nomenclature tab.
  { id: "ven-3", name: "Ackurat Industriplast AB", category: "Supplier", status: "active", country: "Sweden", postCode: "SE-36344", city: "LAMMHULT", address: "Värnamovägen 42", phone: "46472269300" },
  { id: "ven-4", name: "BESTEM Sp.z o.o.", category: "Supplier", status: "active", country: "Poland", postCode: "62210", city: "Zbaszynek", address: "ул. Glowna 57a", vat: "PL7881917600", phone: "889916191", email: "nasko.atanasov@flatrom.bg" },
  { id: "ven-5", name: "BETELGEUS Ltd", category: "Supplier", status: "active", country: "България", postCode: "1186", city: "София", address: "Манастирска Воденица 1", phone: "896689977", email: "labels@betelgeus.com" },
  { id: "ven-6", name: "Bewo Cutting Systems", category: "Supplier", status: "active", country: "The Netherlands", postCode: "5048", city: "RJ Waawalwijk", address: "Van Harenstraat 2", vat: "NL820032281B01", phone: "+ 31 13 467 69 15" },
  { id: "ven-7", name: "Butzbacher Schleifmittel-Werke GmbH", category: "Supplier", status: "active", country: "Germany", postCode: "35510", city: "Butzbach", address: "Alte Wetzlarer Str. 4", phone: "+49 6033 8905-51" },
  { id: "ven-8", name: "Convex Glass Sp.z o.o", category: "Supplier", status: "active", country: "Poland", postCode: "23412", city: "Lukowa", address: "Chmielek 204B", vat: "PL9181748355" },
  { id: "ven-9", name: "DENTAS ROMANIA S.R.L.", category: "Supplier", status: "active", country: "Romania", postCode: "137435", city: "Judetul Dambovita", address: "Str. Dentas nr.32", vat: "RO16011391", phone: "0090 539 705 27 67", email: "Orcun.Mutlu@dentaskagit.com.tr;cristian.matei@dentas.ro" },
  { id: "ven-10", name: "DESE KALIP", category: "Supplier", status: "active", country: "Turkey", city: "Esenyurt / İstanbul", address: "Orhan Gazi Mh. 4. Yol Sk. ISISO San. Sit. H Blok No:33" },
  { id: "ven-11", name: "DONG GUAN ACONIC FABRIC CO., LTD", category: "Supplier", status: "active", country: "China", postCode: "523525", city: "Dong guan", address: "Building 1, No. 8, Qiaoxin West 2nd Road, Qiaotou Town" },
  { id: "ven-12", name: "DRADURA Italia s.r.l.", category: "Supplier", status: "active", country: "Italy", postCode: "15030", city: "Conzano AL", address: "Via Monferato, 4", vat: "IT02106020064" },
  { id: "ven-13", name: "DS smith  България АД", category: "Supplier", status: "active", country: "България", postCode: "4400", city: "Пазарджик", address: "кв. Главиница", phone: "887671338", email: "vera.gencheva@dssmith.com;Aneta.Licheva@dssmith.com;Atanas.Atanasov@dssmith.com" },
  { id: "ven-14", name: "DUNAPACK - Родина", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "бул. Марица  № 97", phone: "888146160", email: "Daniela.Ingova@dunapack-packaging.com;Stanislav.Velev@dunapack-packaging.com" },
  { id: "ven-15", name: "FAR S.r.l", category: "Supplier", status: "active", country: "Italy", postCode: "40057", city: "Granarolo dell'", address: "Via Giovanni XXIII,2 - Loc. Quarto Infer", vat: "IT00687071209", phone: "390516009555" },
  { id: "ven-16", name: "FIXI S.r.l", category: "Supplier", status: "active", country: "Italy", postCode: "10146", city: "Torino", address: "Via Bellardi 40/A", vat: "IT05192950011" },
  { id: "ven-17", name: "Forlit Slovakia a.s.", category: "Supplier", status: "active", country: "Slovakia", city: "Skalica", address: "Sasinkova 2575/4 909 01", vat: "SK1210487292", phone: "421915286403", email: "marcel.melichercik@forlit.eu" },
  { id: "ven-18", name: "Gunestel", category: "Supplier", status: "active", country: "Turkey", city: "Arnavutköy / İstanbul", address: "Ömerli Mh. İhsangazi Sk." },
  { id: "ven-19", name: "HD Lighting Co.,LTD", category: "Supplier", status: "active", country: "China", city: "Guang Dong", address: "4F,No.2, XingXiang Rd, ShengFeng, Xiao Lan Town, Zhong Shan" },
  { id: "ven-20", name: "HMI   Ltd", category: "Supplier", status: "active", country: "България", postCode: "5000", city: "В.Търново", address: "ул.Н.Габровски 81А", phone: "62634609" },
  { id: "ven-21", name: "HT Bendix A/S", category: "Supplier", status: "active", country: "DK", postCode: "7400", city: "Herning", address: "Ronnevej 4", vat: "DK34215685", phone: "4596263311", email: "vissing@ht-bendix.dk" },
  { id: "ven-22", name: "IKEA Components  S.R.O", category: "Supplier", status: "active", country: "Slovakia", postCode: "90101", city: "Malacky", address: "Tovarenska", vat: "SK2020207574", phone: "00421 34 79 64 353" },
  { id: "ven-23", name: "IKEA Components AB", category: "Supplier", status: "active", country: "Sweden", postCode: "34324", city: "ALMHULT", address: "Box600 Sodra Ringvagen 4", phone: "4647682000" },
  { id: "ven-24", name: "Intercom Group Ltd.", category: "Supplier", status: "active", country: "България", postCode: "9009", city: "Варна", address: "Западна индустриална зона", phone: "+359 52 574 210" },
  { id: "ven-25", name: "Julia Utensili SpA", category: "Supplier", status: "active", country: "Italy", postCode: "33017", city: "Tarcento", address: "s.s 13-km 147.5", vat: "IT00567460308", phone: "390432784723" },
  { id: "ven-26", name: "K.Hartwall", category: "Supplier", status: "active", country: "Finland", postCode: "1150", city: "Soderkulla", address: "Kay Hartwallin tie 2" },
  { id: "ven-27", name: "KAMMARTON", category: "Supplier", status: "active", country: "България", city: "Враца", address: "ул. Илиенско шосе №8", phone: "887800761", email: "Miglena.Ilieva@kammarton.com;vraca@kammarton.com" },
  { id: "ven-28", name: "Kovonastroje s.r.o.", category: "Supplier", status: "active", country: "Czech Republic", postCode: "76351", city: "Bohuslavice u Zlina", address: "Bohuslavice u Zlina 205", vat: "CZ05967473", phone: "420602716471", email: "objednavky@kovonastroje.cz" },
  { id: "ven-29", name: "Lektronix Rockwell Automation", category: "Supplier", status: "active", country: "Poland", postCode: "01-797", city: "Warszawa", address: "ul. Powazkowska 44c", vat: "PL1181363444", phone: "+48 22 459 6690" },
  { id: "ven-30", name: "MARBET Sp. z.o.o", category: "Supplier", status: "active", country: "POLAND", postCode: "43-346", city: "Bielsko-Biala", address: "str.Chocholowska 28", vat: "PL5471941897", phone: "480338127149" },
  { id: "ven-31", name: "Metal Tehnologija D.O.O", category: "Supplier", status: "active", country: "Bosna i Hercegovina", postCode: "74400", city: "Derventa", address: "ul. Kninska bb", vat: "402872990009", phone: "00387/53334688" },
  { id: "ven-32", name: "Meusburger Georg GmbH Co KG", category: "Supplier", status: "active", country: "Austria", postCode: "6960", city: "Wolfurt", address: "Kesselstr. 42", vat: "ATU49325305", phone: "35924925149" },
  { id: "ven-33", name: "NTI Company", category: "Supplier", status: "active", country: "Poland", postCode: "43-300", city: "Bielsko-Biala", address: "Teodora Tomasza Jeza 10", email: "mariusz.kieczka@nticompany.eu" },
  { id: "ven-34", name: "Paul Thoors GMBH", category: "Supplier", status: "active", country: "Germany", postCode: "53909", city: "Zülpich- Mülhei", address: "Pescher Str. 20", phone: "+49 (0)2252-1577" },
  { id: "ven-35", name: "PPW Manufacturing AB", category: "Supplier", status: "active", country: "Sweden", postCode: "330 10", city: "Bredaryd", address: "Albanovägen 11", phone: "+46 (0)705-55 92 63" },
  { id: "ven-36", name: "Precitec GmbH & Co. KG", category: "Supplier", status: "active", country: "Germany", postCode: "D-76571", city: "Gaggenau", address: "Draisstrasse 1", phone: "4972256840", email: "precitec@precitec.de" },
  { id: "ven-37", name: "RAMO MATERIAL AB", category: "Supplier", status: "active", country: "Sweden", postCode: "33125", city: "Varnamo", address: "box511", phone: "46370378700" },
  { id: "ven-38", name: "REKA Klebetechnik Gmbh", category: "Supplier", status: "active", country: "Germany", postCode: "76344", city: "Eggenstein", address: "Siemensstr 6" },
  { id: "ven-39", name: "ROBCON TM SRL", category: "Supplier", status: "active", country: "РУМЪНИЯ", city: "Тимишоара", address: "Eleas  10" },
  { id: "ven-40", name: "R-pac", category: "Supplier", status: "active", country: "Hungary", postCode: "4030", city: "Debrecen", address: "Vámraktár 3/B1, 4030, Debrecen", phone: "+49 (0) 2324 344 98 92", email: "tanja.soefken@r-pac.com" },
  { id: "ven-41", name: "RSA cutting systems GmbH", category: "Supplier", status: "active", country: "DEUTSCHLAND", postCode: "58513", city: "Ludenscheid", address: "Fraisenbergstrase  19", phone: "0049 2351 995 5" },
  { id: "ven-42", name: "S.C. ROMSPIRIT SRL", category: "Supplier", status: "active", country: "Romania", postCode: "5164179", city: "Brasov", address: "str.SITARULI", vat: "RO5164179", phone: "0374/068262" },
  { id: "ven-43", name: "SC AMBRO SA", category: "Supplier", status: "active", country: "Romania", postCode: "720019", city: "Suceava", address: "Calea Unirii no 24", vat: "RO2691530", phone: "40230205144" },
  { id: "ven-44", name: "SCHÄFER WERKE GmbH", category: "Supplier", status: "active", country: "Germany", postCode: "1120", city: "Neunkirchen", address: "Pfannenbergstrasse 1", phone: "2.7357873769999999E-2" },
  { id: "ven-45", name: "Schlatter Industries AG", category: "Supplier", status: "active", country: "SWITZERLAND", postCode: "8952", city: "SCHLIEREN", address: "Brandstrasse 24" },
  { id: "ven-46", name: "SEDO VINA", category: "Supplier", status: "active", country: "Vietnam", email: "sales1@sedovina.com" },
  { id: "ven-47", name: "Sherwin-Williams Balkan SRL", category: "Supplier", status: "active", country: "Romania", city: "Chisoda", address: "DN 59 KM 8 + 550m STANGA", vat: "RO22483313" },
  { id: "ven-48", name: "SIAT S.p.A.", category: "Supplier", status: "active", country: "Italy", postCode: "33013", city: "Gemona del Friuli (UD)", address: "Via Facini, 54" },
  { id: "ven-49", name: "Smurfit Kappa България ЕООД", category: "Supplier", status: "active", country: "България", postCode: "5770", city: "Луковит", address: "ул. Христо Ботев 57", phone: "888736376", email: "Radostina.Doncheva@smurfitwestrock.bg" },
  { id: "ven-50", name: "Sorst Streckmetall GmbH", category: "Supplier", status: "active", country: "Germany", postCode: "30179", city: "Hannover", address: "Wohlenbergstrasse 11", phone: "+49 (0) 511 / 67 67 56 5" },
  { id: "ven-51", name: "Tempo - el", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "ул. Георги  Трингов  № 11" },
  { id: "ven-52", name: "TME", category: "Supplier", status: "active", country: "Полша", postCode: "93-350", city: "Lodz", address: "Ustronna", vat: "PL7290108984", email: "export@tme.eu." },
  { id: "ven-53", name: "TOME", category: "Supplier", status: "active", country: "България", postCode: "2880", city: "Габрово", address: "ул. Орловска 129", phone: "66810555" },
  { id: "ven-54", name: "TVT", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "бул. искарско шосе 7", phone: "885777507", email: "m.petrov@tvt.bg" },
  { id: "ven-55", name: "ULBRICH Maschinenbau- und Export-Import Betriebsg.m.b.H", category: "Supplier", status: "active", country: "Austria", postCode: "A-2512", city: "Tribuswinkel", address: "Josefstahler Strasse 34", vat: "AT U17572204" },
  { id: "ven-56", name: "Ultrapolymers Group Bulgaria", category: "Supplier", status: "active", country: "България", postCode: "1360", city: "София", address: "Обелско Шосе 12" },
  { id: "ven-57", name: "UYGUR", category: "Supplier", status: "active", country: "Turkey", postCode: "34538", city: "Esenyurt – Istanbul", address: "Orhangazi Mahallesi,1664 Sokak, No:15", vat: "8980075551", phone: "2165442271" },
  { id: "ven-58", name: "Venex", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. Бурел бл.72А", vat: "BG831353771", phone: "898416532", email: "office@ven-ex.eu" },
  { id: "ven-59", name: "Ying Han Technology Sp.", category: "Supplier", status: "active", country: "Taiwan", city: "Tainan", address: "NO.240, CHUNG CHENG ROAD" },
  { id: "ven-60", name: "Адриан - 95 ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ул. Иван Аврамов 30", phone: "888702874" },
  { id: "ven-61", name: "Актуал Индъстрис ООД", category: "Supplier", status: "active", country: "България", postCode: "4003", city: "Пловдив", address: "ул. Рогошко шосе № 6", phone: "359886555900", email: "info@actual-industries.com;zhivko.indjov@actual-industries.com" },
  { id: "ven-62", name: "Албако Импекс ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "Бул. Янко Сакъзов 19", phone: "878937073", email: "haralambiev@albaco-bg.com" },
  { id: "ven-63", name: "АЛИТЕХ ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "4470", city: "БЕЛОВО", address: "Ул.\"ВАСИЛ ЛЕВСКИ\"1", vat: "BG205104357" },
  { id: "ven-64", name: "АМЕТ ООД", category: "Supplier", status: "active", country: "България", postCode: "1331", city: "София", address: "бул.Европа 177" },
  { id: "ven-65", name: "Ангел Стоилов-96 АД", category: "Supplier", status: "active", country: "България", city: "София", address: "ул. Ил. Бешков 3", phone: "29731770" },
  { id: "ven-66", name: "Анейк ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "Младост 1А, бл.519, ап.24", phone: "887720999", email: "androneyk@abv.bg" },
  { id: "ven-67", name: "Анис - В ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ж.к.Дървеница бл.40", vat: "BG175150965" },
  { id: "ven-68", name: "АТРИ РОБОТИКС ЕООД", category: "Supplier", status: "active", country: "България", postCode: "6000", city: "Стара Загора", address: "ул.Цар Иван Шишман 77", vat: "BG206099964" },
  { id: "ven-69", name: "Аутопрофи България Co ООД", category: "Supplier", status: "active", country: "България", postCode: "1712", city: "София", address: "ж.к Младост 3 бл 327 вх.В ет.6 ап.85", phone: "879548060" },
  { id: "ven-70", name: "АХАТ", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "Индустриална  23", phone: "96306155" },
  { id: "ven-71", name: "Балкан АД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ул. Парта, 12", phone: "96300010" },
  { id: "ven-72", name: "Балкан Стийл Инженеринг", category: "Supplier", status: "active", country: "България", postCode: "1111", city: "София", address: "кв Казичене", phone: "29711109" },
  { id: "ven-73", name: "Балкан Юг ООД", category: "Supplier", status: "active", country: "България", postCode: "6300", city: "Хасково", address: "ул. Съединение 66", vat: "BG126105276" },
  { id: "ven-74", name: "Баркод Системи България ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "София", phone: "882110094" },
  { id: "ven-75", name: "Баш Майстора", category: "Supplier", status: "active", country: "България", postCode: "9000", city: "Варна", address: "ул. Струга\" 23" },
  { id: "ven-76", name: "БГ Машини ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ж.к Враждебна ул. 1-ва  5", vat: "BG202142790" },
  { id: "ven-77", name: "Бестимекс ООД", category: "Supplier", status: "active", country: "България", postCode: "1606", city: "София", address: "ул. Бузлуджа 5", phone: "9265858" },
  { id: "ven-78", name: "БУЛВАРИЯ АТОМОБИЛНИ ПРОДУКТИ ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1324", city: "София", address: "ул. Орион 84", vat: "BG131018442", phone: "882042000", email: "mariyan.todorov@cyclon.bg" },
  { id: "ven-79", name: "БУЛТЕХНОХИМ", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "Хан  Омуртаг  № 72 ет.1", phone: "0887 76 44 34" },
  { id: "ven-80", name: "ВАЛИМАР ООД", category: "Supplier", status: "active", country: "България", city: "Варна", address: "бул. Цар Освободител 230", phone: "52510300" },
  { id: "ven-81", name: "ВИАХИМ  ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "кв. Горна баня ул. 757  №26", phone: "884699377" },
  { id: "ven-82", name: "Вида винт ООД", category: "Supplier", status: "active", country: "България", city: "Враца", address: "ул. Никола Вапцаров 1", phone: "879144969" },
  { id: "ven-83", name: "ВИДА СЕЙФТИ ЕООД", category: "Supplier", status: "active", country: "България", city: "Видин", address: "ул. Найчо Цанов", phone: "878852044" },
  { id: "ven-84", name: "ВИКИВАТ ООД", category: "Supplier", status: "active", country: "България", postCode: "4003", city: "Пловдив", address: "ул. Тича №17", vat: "BG160138003", phone: "032/643219", email: "dpo@vikiwat.com" },
  { id: "ven-85", name: "Вюрт България ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "Бизнес парк София", phone: "882828991", email: "Radostina.Yoncheva@wuerth.bg" },
  { id: "ven-86", name: "ГЕВАГ България  ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "Поп Богомил №3", phone: "888722918" },
  { id: "ven-87", name: "Геомат 2 - ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "жк. Орландовци, ул. Нешо Бончев №26 ет.4", vat: "BG200240613", phone: "359886435703", email: "geomat@abv.bg" },
  { id: "ven-88", name: "Глобъл Линкс ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1301", city: "София", address: "ул. Позитано 5", vat: "BG131177940" },
  { id: "ven-89", name: "Дано ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", phone: "306590" },
  { id: "ven-90", name: "ДЕКАР-М    ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1110", city: "СОФИЯ", address: "ул.  ПРЕЛОМ  №2", phone: "899888703", email: "office@dekar-m.com" },
  { id: "ven-91", name: "Деником ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ПЪТ Е79", phone: "886757000", email: "montana.office@denicom.bg" },
  { id: "ven-92", name: "Джесур Груп ООД К.Ю.Садул", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София" },
  { id: "ven-93", name: "Дикозо ЕООД", category: "Supplier", status: "active", country: "България", city: "Пловдив", address: "ул. Цар Асен 9", vat: "BG115575381" },
  { id: "ven-94", name: "Дилком България ЕООД", category: "Supplier", status: "active", country: "България", postCode: "9000", city: "Варна", address: "ул. Нептун 2", phone: "884669024", email: "i.gachevska@dilcom.com" },
  { id: "ven-95", name: "Динела  ООД", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "ул. Правда 2" },
  { id: "ven-96", name: "ДТЛ ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София" },
  { id: "ven-97", name: "Евромаркет БРД ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "Плевен", phone: "64600082" },
  { id: "ven-98", name: "Екогалваник ООД", category: "Supplier", status: "active", country: "България", city: "Русе", address: "Тутракан 100" },
  { id: "ven-99", name: "ЕкоТОК ЕООД", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "ул. Бъдеще 39" },
  { id: "ven-100", name: "ЕЛЕКС- МИЗИЯ   ООД", category: "Supplier", status: "active", country: "България", postCode: "5800", city: "Плевен", address: "Хан  Аспарух 18", phone: "886535070", email: "elecs_vratza@abv.bg" },
  { id: "ven-101", name: "Елимекс Иженеринг ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "Горна Оряховица", address: "ул. Мадара №1", vat: "BG201543524" },
  { id: "ven-102", name: "ЕЛСТРОй-2003 ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "3400", city: "МОНТАНА", address: "\"ГОЦО МИТОВ\"11", vat: "BG111547089" },
  { id: "ven-103", name: "ЕМ Комерс 10 ЕООД", category: "Supplier", status: "active", country: "България", city: "Русе", phone: "82819224" },
  { id: "ven-104", name: "ЕМА 78 ЕООД", category: "Supplier", status: "active", country: "България", postCode: "5800", city: "Плевен", address: "ул. Гена Димитрова 18", vat: "BG203213767", phone: "885251602", email: "ema78.eood@gmail.com" },
  { id: "ven-105", name: "ЕМА ООД", category: "Supplier", status: "active", country: "България", postCode: "5800", city: "Плевен", address: "ул. Дойран 160", phone: "888822895", email: "rachev@ema-bg.com" },
  { id: "ven-106", name: "ЕМА ООД офис", category: "Supplier", status: "active", country: "България", postCode: "5800", city: "Плевен", address: "ул. Дойран  № 160" },
  { id: "ven-107", name: "ЕМЦ ДИСТРИБЮШЪН ЕООД", category: "Supplier", status: "active", country: "България", postCode: "7000", city: "Русе", address: "бул. Тутракан 100", vat: "BG202339357", phone: "082/819256" },
  { id: "ven-108", name: "ЕНИВИТИ ООД", category: "Supplier", status: "active", country: "България", postCode: "5800", city: "Плевен", address: "бул Българска Авиация 37", phone: "64849168" },
  { id: "ven-109", name: "ЕПГ 2015 ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", phone: "888464220", email: "epg2015@abv.bg" },
  { id: "ven-110", name: "Ер Ликид България", category: "Supplier", status: "active", country: "България", postCode: "2070", city: "Пирдоп", address: "Индустриална зона", vat: "BG130059799" },
  { id: "ven-111", name: "Ес Джи Ес България", category: "Supplier", status: "active", country: "България", city: "София", address: "Овча Купел, ул. Кукуряк 12", phone: "885248405" },
  { id: "ven-112", name: "ЕТ \" Иван-Александър- Николай Изов\"", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "бул. Първа Българска Армия 81" },
  { id: "ven-113", name: "ЕТ Досев и син", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "Монтана" },
  { id: "ven-114", name: "ЕТ Мария Грозданова", category: "Supplier", status: "active", country: "България", city: "София", address: "кв. Ботунец 2 бл. 13 - Б - 38" },
  { id: "ven-115", name: "ЕТ РОМИНЕЛА - Мария Нешева", category: "Supplier", status: "active", country: "България", city: "Карлово", address: "ул. Тодорр Каблешков 44А", vat: "BG825070288", email: "nesho1957@abv.bg" },
  { id: "ven-116", name: "ЕТ Теодора - Грета Кръстева", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана" },
  { id: "ven-117", name: "ЕТ\"СЕВЛИН -Севлин Гоцов\"", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "3400", city: "Монтана", vat: "BG 821116076" },
  { id: "ven-118", name: "Жити АД", category: "Supplier", status: "active", country: "България", postCode: "7000", city: "Русе", address: "бул.Трети Март 30", vat: "BG827183411" },
  { id: "ven-119", name: "ЗАВОД ЗА ПРУЖИНИ АД", category: "Supplier", status: "active", country: "България", postCode: "6140", city: "Крън", address: "ул.Работническа 2", vat: "BG123132147" },
  { id: "ven-120", name: "ЗАИ АД", category: "Supplier", status: "active", country: "България", city: "Берковица", address: "ул. Николаевска 100", phone: "885515882", email: "i.avramov_sales@zai-bg.com" },
  { id: "ven-121", name: "ЗИП - М - 2008 ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ул.Св.Климент Охридски 52" },
  { id: "ven-122", name: "ЗПТ Трейд", category: "Supplier", status: "active", country: "България", city: "София", address: "129 А Челопеченско шосе", phone: "24915837" },
  { id: "ven-123", name: "ИГРЕ-К2017 ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "ул. Петко Д. Петков 4, ет.2 ап. 7" },
  { id: "ven-124", name: "Импекстим ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ж.к. „Младост 4“, ул. „Околовръстен път“ №251 Г, ММ Бизнес център, ет.3, офис 302", phone: "888333592", email: "s.zahova@impextim.com" },
  { id: "ven-125", name: "Индустриал пак ЕООД", category: "Supplier", status: "active", country: "България", city: "Пловдив", address: "бул. Цариградско шосе", vat: "BG204481372" },
  { id: "ven-126", name: "Интернешънъл стийл тюбс АД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "бул. „Витоша” 3, ет.6", vat: "BG206334788", email: "j.milenkova@fusionplastics.eu" },
  { id: "ven-127", name: "Ирбис Сейфти ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "ул. Борис Стефанов № 16", phone: "02 8 665 415" },
  { id: "ven-128", name: "ИТТ България ООД", category: "Supplier", status: "active", country: "България", postCode: "6000", city: "Ст.Загора", address: "ул. Хрищенско шосе № 30", phone: "042 66 10 36" },
  { id: "ven-129", name: "ЙОВ България ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1186", city: "Герман", address: "ул. Смреката 3", vat: "BG131111220", phone: "35929928443", email: "iow@iow.bg" },
  { id: "ven-130", name: "Йотун България ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "Гюешево 83", phone: "9201123" },
  { id: "ven-131", name: "КАНДЕКС ГРУП ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "ВАРНА", address: "ул. Брегалница 1", vat: "BG103132143" },
  { id: "ven-132", name: "КНИЖНА ФАБРИКА ИСКЪР - АД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "гара ИСКЪР, ул. 5004-та 1", vat: "BG121022677", phone: "887352570", email: "sales_kfi@abv.bg" },
  { id: "ven-133", name: "КРЕМАПЛАСТ  ООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ул. Поп Пунчо", phone: "888683285", email: "kremaplastood@abv.bg" },
  { id: "ven-134", name: "ЛАН Лилов Ангелов Нешев и Сие СД", category: "Supplier", status: "active", country: "България", postCode: "3900", city: "Белоградчик", address: "Васил Левски № 23", phone: "887580517", email: "Atanas Lilov JLN <jln_Lilov@abv.bg>" },
  { id: "ven-135", name: "Лейбер Газ  ООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "ул. Екзарх  Йосифов  19", phone: "887367358" },
  { id: "ven-136", name: "Лена ООД", category: "Supplier", status: "active", country: "България", city: "Сливен", phone: "44667324" },
  { id: "ven-137", name: "Лесто Продукт ООД", category: "Supplier", status: "active", country: "България", city: "Враца", address: "ул. Г.Апостолов", phone: "92661093" },
  { id: "ven-138", name: "Майнинг ООД", category: "Supplier", status: "active", country: "България", city: "София", address: "бул. Шипченски проход 18, ет. 2", vat: "BG130671084" },
  { id: "ven-139", name: "МАКС МЕТАЛ ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "бул. България 86А, ет.4", vat: "BG175206734" },
  { id: "ven-140", name: "МАКСТЕХНИК - ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "ПЛОВДИВ", address: "\"Иларион Макариополски\"108", vat: "BG205218971" },
  { id: "ven-141", name: "Мастер - 11 ЕООД", category: "Supplier", status: "active", country: "България", postCode: "4003", city: "Пловдив", address: "ул. Братя Стърневи 47", vat: "BG115138289", phone: "8880938340", email: "master11.office@gmail.com" },
  { id: "ven-142", name: "МЕСЕР България ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1528", city: "София", address: "Димитър Пешев 3А", phone: "1111111" },
  { id: "ven-143", name: "Мивела лайт ЕООД", category: "Supplier", status: "active", country: "България", city: "Панагюрище", address: "ул. Георги Нейчев 7", vat: "BG202316885" },
  { id: "ven-144", name: "ММ Политрейд ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул.Траян Танев №78", vat: "BG131371713" },
  { id: "ven-145", name: "Нова книжна  фабрика", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. 5004 № 1", phone: "878191520", email: "sales@nkfabrika.com" },
  { id: "ven-146", name: "Омникар БГ ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. Индустриална 11", phone: "886343899" },
  { id: "ven-147", name: "Офисе оан Монтана", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "Трети март 66", phone: "303569" },
  { id: "ven-148", name: "ПАКИН ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1700", city: "София", address: "ул. Околовръстен път 149, ет.2", phone: "+359 883 29 78 08", email: "gundev@packin.net" },
  { id: "ven-149", name: "ПИРИНПЛАСТ АД", category: "Supplier", status: "active", country: "България", postCode: "2900", city: "Гоце Делчев", address: "Промишлена зона", email: "pirinplast@pirinplast.com" },
  { id: "ven-150", name: "ПИХ ИНДЪСТРИ АД", category: "Supplier", status: "active", country: "България", city: "Русе", phone: "82819224" },
  { id: "ven-151", name: "ПМ АУТОМЕЙШЪН ЕАД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "4199", city: "ТРУД", address: "Карловско шосе 37", vat: "BG207178884" },
  { id: "ven-152", name: "ПМ ЕЛЕКТРИКАЛ ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "1000", city: "СОФИЯ", address: "\"ЦАР АСЕН\" 44", vat: "BG201557416" },
  { id: "ven-153", name: "ПМБ Индъстрис ООД", category: "Supplier", status: "active", country: "България", postCode: "4400", city: "Пазарджик", address: "ул. \"Мильо войвода\" 18", vat: "BG160121541", phone: "899907281", email: "m.bonchev@pmbindustries.com" },
  { id: "ven-154", name: "Покрития ЕООД", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "София", address: "Модерно предградие", phone: "0877992554`" },
  { id: "ven-155", name: "Полимер концепт ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1233", city: "София", address: "ул. Враня № 67, вх. Б, ет. 5, ап. 25", vat: "BG204397793", phone: "885809559", email: "r.donev@polymerconcept.bg" },
  { id: "ven-156", name: "Полимета С", category: "Supplier", status: "active", country: "България", postCode: "1528", city: "София", address: "ж.к. Дружба 1, ул. Илия Бешков 3", phone: "02/ 973 29 04" },
  { id: "ven-157", name: "Практика БГ ООД", category: "Supplier", status: "active", country: "България", city: "София", address: "Професор Цветан Лазаров, 50", phone: "29790970" },
  { id: "ven-158", name: "ПРЕСФОРМ  ООД", category: "Supplier", status: "active", country: "България", postCode: "357", city: "ПАНАГЮРИЩЕ", address: "ул. Г.Нейчев №7", phone: "3575183" },
  { id: "ven-159", name: "Първа частна печатница", category: "Supplier", status: "active", country: "България", postCode: "3400", city: "Монтана", address: "Монтана  , ул.  Шишман № 9", phone: "887560308", email: "kris.print@abv.bg" },
  { id: "ven-160", name: "Редко ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "Дружба 2 ул Обиколна 7", phone: "889954545", email: "sales@redco.bg" },
  { id: "ven-161", name: "Река България ЕООД", category: "Supplier", status: "active", country: "България", city: "София", phone: "894727157", email: "Mario.Ivanov@reca.co.at" },
  { id: "ven-162", name: "РИГЕЛЕТ ООД", category: "Supplier", status: "active", country: "България", postCode: "6000", city: "Ст.Загора", address: "ул. Иречек №21", vat: "200639391", phone: "895523333", email: "office@rigelet.com;supply@rigelet.com" },
  { id: "ven-163", name: "Рода България 09 ООД", category: "Supplier", status: "active", country: "България", postCode: "2303", city: "Перник", address: "ул.Рашо Димитров 123", vat: "BG200782261" },
  { id: "ven-164", name: "Светът на инструментите - България ООД", category: "Supplier", status: "active", country: "България", postCode: "1202", city: "София", address: "Малашевска 8/С3", phone: "897117072" },
  { id: "ven-165", name: "СД  Живков Лилов Нешев и Сие", category: "Supplier", status: "active", country: "България", city: "Белоградчик", address: "Н. Казанджи No 37", phone: "887575006", email: "jln_lilov@abv.bg" },
  { id: "ven-166", name: "Сигма Мет ЕООД", category: "Supplier", status: "active", country: "България", city: "Перник", address: "пл. \"Кракра Пернишки\" 8/1", phone: "76604504" },
  { id: "ven-167", name: "Сидма България ЕАД", category: "Supplier", status: "active", country: "България", city: "София", address: "Илиянци" },
  { id: "ven-168", name: "Славей 91 ООД", category: "Supplier", status: "active", country: "България", city: "София", address: "ул. Чепинско шосе 15", phone: "889631899", email: "sales@slavey91.com" },
  { id: "ven-169", name: "Солдар ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ж.к Овча Купел 2, бл.29Б, вх.А", vat: "BG205407333" },
  { id: "ven-170", name: "СолТех ЕООД", category: "Supplier", status: "active", country: "България", postCode: "4205", city: "Костиево", address: "ул. Капитан Бураго", phone: "32500425" },
  { id: "ven-171", name: "Спрейтех БГООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. Свиленица 14", vat: "BG205691890" },
  { id: "ven-172", name: "Старс Трейдинг ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. Околовръстен път 487А", phone: "886440199", email: "sales.sofia@starstrading.eu" },
  { id: "ven-173", name: "СТИГ - Специални телове и гвоздеи АД", category: "Supplier", status: "active", country: "България", postCode: "7000", city: "Русе", address: "пл. Света Троица 3", phone: "082/826 276" },
  { id: "ven-174", name: "СТИМА ИНЖЕНЕРИНГ ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", postCode: "1000", city: "СОФИЯ", address: "ГЕН.МИХАИЛ САВОВ 5", vat: "BG201476075" },
  { id: "ven-175", name: "Судал ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1138", city: "София", address: "Бул. \"Цариградско шосе\" № 425", vat: "BG175112224", phone: "876672705", email: "Petrov@soudal.bg" },
  { id: "ven-176", name: "Сун-България-ЕООД", category: "Supplier", status: "active", country: "България", city: "Хасково", address: "Отец Паисий 25-27", phone: "38680380" },
  { id: "ven-177", name: "Таневпласт ООД", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "Княгиня Мария Луиза 34", vat: "BG200492233" },
  { id: "ven-178", name: "Техноколор ООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "Гюешево 83", phone: "9201123" },
  { id: "ven-179", name: "ТИВИ ГРУП ИНДЪСТРИ ООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "ДИМИТРОВГРАД", address: "ВИЛХЕЛМ ПИК 10", vat: "BG126651624" },
  { id: "ven-180", name: "Тисенкруп - Юпитер Стомана ООД", category: "Supplier", status: "active", country: "България", postCode: "1839", city: "София", address: "кв. Враждебна", vat: "BG131474168", phone: "+359 2 942 7877" },
  { id: "ven-181", name: "ТМТ - Елком ООД", category: "Supplier", status: "active", country: "България", city: "Пловдив", address: "ул. Цариградско шосе № 53А", phone: "32621431" },
  { id: "ven-182", name: "Томес ЕООД", category: "Supplier", status: "active", country: "България", city: "София", address: "ул. Люботрън 11", phone: "889229383" },
  { id: "ven-183", name: "Топливо Газ ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ж.к Хаджи Димитър", vat: "BG130864186" },
  { id: "ven-184", name: "Топтекс протекст ЕООД", category: "Supplier", status: "active", country: "България", postCode: "4000", city: "Пловдив", address: "жк. Тракия, бул. Цар Борис 3ти" },
  { id: "ven-185", name: "Тракия дизайн", category: "Supplier", status: "active", country: "България", postCode: "6000", city: "Стара Загора", address: "ул. Дунав № 6, ет. 5, ап.7", vat: "BG200658922", phone: "878235458" },
  { id: "ven-186", name: "УАЙЪР   ООД", category: "Supplier", status: "active", country: "България", postCode: "1111", city: "Роман", address: "ул.   ИСКЪР   15", phone: "91233825" },
  { id: "ven-187", name: "Универсалстрой ООД", category: "Supplier", status: "active", country: "България", city: "Троян", address: "Д.Икономов 32", phone: "35969552320", email: "ustroi@abv.bg" },
  { id: "ven-188", name: "Фидан Индъстри ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1164", city: "София", address: "ул. Храламби Тачев” 4", vat: "BG131104603", email: "j.milenkova@fusionplastics.eu" },
  { id: "ven-189", name: "Флексикон БГ ЕООД", category: "Supplier", status: "active", country: "България", city: "Банкя", address: "ул. Тунджа 1", vat: "BG108512911", phone: "888564174", email: "flexicon.bg@gmail.com" },
  { id: "ven-190", name: "Формо ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "гр. София", address: "бул. Илиянци 42 (КЗУ), ет. 6", phone: "+359 (0) 988 885504" },
  { id: "ven-191", name: "Фьорх България  ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "София", address: "ул. Новото  ливаде 2", vat: "882471884" },
  { id: "ven-192", name: "ХАИТИАН БЪЛГАРИЯ ЕООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "Кърджали", address: "бъул. България 101", vat: "BG206552737" },
  { id: "ven-193", name: "ХИД-ТЕК ООД", category: "Supplier", status: "active", country: "БЪЛГАРИЯ", city: "Пловдив", address: "ул. Васил Левски №52, ет.1, офис 1", vat: "BG108530592" },
  { id: "ven-194", name: "ХОРТЕХ ЕООД", category: "Supplier", status: "active", country: "България", postCode: "1000", city: "Стамболийски", address: "ул. Кочо Честименски" },
  { id: "ven-195", name: "ХЪС ООД", category: "Supplier", status: "active", country: "България", postCode: "3600", city: "Лом", address: "ул. Индустриална №1", phone: "896733781", email: "daniela.parvanova@husltd.com" },
]

/** @type {import('./model.js').Material[]} */
export const materials = [
  { id: 'mat-1', sku: 'RM-TUBE-25', name: 'Steel tube Ø25×1.5 S235JR', uom: 'kg' },
  { id: 'mat-2', sku: 'RM-PACK-01', name: 'Fittings bag + flat-pack carton', uom: 'ea' },
]

/** @type {import('./model.js').PurchaseOrder[]} */
export const purchaseOrders = [
  { id: 'po-1', vendorId: 'ven-1', orderedAt: '2026-03-01', status: 'received' },
  { id: 'po-2', vendorId: 'ven-2', orderedAt: '2026-04-02', status: 'partial' },
  { id: 'po-3', vendorId: 'ven-1', orderedAt: '2026-04-08', status: 'sent' },
]

/** @type {import('./model.js').PurchaseOrderLine[]} */
export const purchaseOrderLines = [
  { id: 'pol-1', purchaseOrderId: 'po-1', materialId: 'mat-1', qty: 500, unitCost: 2.4 },
  { id: 'pol-2', purchaseOrderId: 'po-2', materialId: 'mat-2', qty: 2000, unitCost: 0.35 },
  { id: 'pol-3', purchaseOrderId: 'po-3', materialId: 'mat-1', qty: 320, unitCost: 2.55 },
]

/** @type {import('./model.js').GoodsReceipt[]} */
export const goodsReceipts = [
  { id: 'gr-1', purchaseOrderId: 'po-1', receivedAt: '2026-03-10', lineId: 'pol-1' },
  { id: 'gr-2', purchaseOrderId: 'po-2', receivedAt: '2026-04-05', lineId: 'pol-2' },
]

/** @type {import('./model.js').VendorInvoice[]} */
export const vendorInvoices = [
  { id: 'vinv-1', vendorId: 'ven-1', purchaseOrderId: 'po-1', amount: 1200, issuedAt: '2026-03-11' },
  { id: 'vinv-2', vendorId: 'ven-2', purchaseOrderId: 'po-2', amount: 420, issuedAt: '2026-04-06' },
]
