/** @type {import('./model.js').Product[]} */
export const products = [
  // ── Manufactured products (finished goods for IKEA) ────────────────────────
  {
    id: 'prod-1',
    sku: 'IKEA-ADILS-W',
    name: 'ADILS Table Leg 70 cm (white)',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'Powder-coated steel tube leg with welded mounting plate and adjustable foot',
    lifecyclePhaseId: 'production',
  },
  {
    id: 'prod-2',
    sku: 'IKEA-LERBERG-G',
    name: 'LERBERG Shelf Side Frame (grey)',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'Press-bent steel side frame for LERBERG shelf unit, powder grey',
    lifecyclePhaseId: 'quality',
  },
  {
    id: 'prod-3',
    sku: 'IKEA-VIKA-CURRY',
    name: 'VIKA CURRY Leg (discontinued)',
    status: 'archived',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: false,
    lifecyclePhaseId: 'released',
  },

  // ── Packaged product (manufactured + externally sourced components) ─────────
  {
    id: 'prod-pkg-1',
    sku: 'PKG-LERBERG-SET',
    name: 'LERBERG Frame Set (retail pack)',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'Retail-packed LERBERG side frame with fittings bag and flat-pack carton',
    lifecyclePhaseId: 'concept',
  },

  // ── Raw materials (purchased, consumed in BoMs) ─────────────────────────────
  {
    id: 'prod-rm-1',
    sku: 'RM-TUBE-25',
    name: 'Steel Tube Ø25×1.5 mm (S235JR)',
    status: 'active',
    type: 'raw_material',
    uom: 'kg',
    uom2: 'm',
    uomCoef: 0.333,
    priceAverage: 1.45,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Cold-rolled steel tube, 6 m bars, for table-leg production',
  },
  {
    id: 'prod-rm-2',
    sku: 'RM-FAST-M6',
    name: 'M6 Zinc Fasteners',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 0.05,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
  },
  {
    id: 'prod-rm-3',
    sku: 'RM-SHEET-2',
    name: 'Steel Sheet Blank 2 mm (laser-cut)',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 12.50,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Pre-cut DC01 sheet blank for LERBERG frame bending',
  },
  {
    id: 'prod-rm-4',
    sku: 'RM-CAP-SET',
    name: 'End Cap & Foot Set (plastic)',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 0.85,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
  },
  {
    id: 'prod-rm-5',
    sku: 'RM-PACK-01',
    name: 'Fittings Bag + Flat-Pack Carton',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 1.10,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Externally sourced retail packaging per IKEA pack spec',
  },
]
