/** @type {import('./model.js').Product[]} */
export const products = [
  // ── Manufactured products (finished goods) ─────────────────────────────────
  {
    id: 'prod-1',
    sku: 'SKU-1001',
    name: 'Precision Housing',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'CNC-machined aluminium housing',
    lifecyclePhaseId: 'production',
  },
  {
    id: 'prod-2',
    sku: 'SKU-1002',
    name: 'Control Module',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'PCBA + firmware bundle',
    lifecyclePhaseId: 'quality',
  },
  {
    id: 'prod-3',
    sku: 'SKU-1003',
    name: 'Legacy Bracket',
    status: 'archived',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: false,
    lifecyclePhaseId: 'released',
  },

  // ── Packaged product (manufactured + externally sourced components) ─────────
  {
    id: 'prod-pkg-1',
    sku: 'PKG-2026-0001',
    name: 'Electronics Package A',
    status: 'active',
    type: 'finished_good',
    uom: 'ea',
    canBePurchased: false,
    canBeManufactured: true,
    canBeSold: true,
    description: 'Packaged Control Module with ESD tray — ready for shipment',
    lifecyclePhaseId: 'concept',
  },

  // ── Raw materials (purchased, consumed in BoMs) ─────────────────────────────
  {
    id: 'prod-rm-1',
    sku: 'RM-AL-01',
    name: 'Aluminium Plate 6061 (12 mm)',
    status: 'active',
    type: 'raw_material',
    uom: 'kg',
    uom2: 'm',
    uomCoef: 0.333,
    priceAverage: 4.80,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Stock-size billet for CNC machining',
  },
  {
    id: 'prod-rm-2',
    sku: 'RM-FAST-01',
    name: 'M4 Steel Fasteners',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 0.05,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
  },
  {
    id: 'prod-rm-3',
    sku: 'RM-PCB-01',
    name: 'PCB Blank (rev 3)',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 12.50,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Bare 4-layer PCB for Control Module assembly',
  },
  {
    id: 'prod-rm-4',
    sku: 'RM-IC-01',
    name: 'MCU IC STM32F4',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 8.20,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
  },
  {
    id: 'prod-rm-5',
    sku: 'RM-ESD-01',
    name: 'ESD Tray',
    status: 'active',
    type: 'raw_material',
    uom: 'ea',
    priceAverage: 1.10,
    canBePurchased: true,
    canBeManufactured: false,
    canBeSold: false,
    description: 'Externally sourced anti-static packaging tray',
  },
]
