/** @type {import('./model.js').Operation[]} */
export const operations = [
  {
    id: 'op-1',
    productId: 'prod-1',
    sequence: 1,
    name: 'CNC mill',
    stepCode: 'mill',
    status: 'done',
    machineId: 'mach-1',
    standardMinutes: 48,
    siloId: 'silo-machining',
    silo: 'Machining cell',
    ownerId: 'emp-1',
    stationCode: 'ST-CNC-01',
    dailyKpiTarget: { targetUnitsPerShift: 96, maxDefectRatePercent: 1.5, targetCycleMinutes: 47 },
  },
  {
    id: 'op-2',
    productId: 'prod-1',
    sequence: 2,
    name: 'Deburr',
    stepCode: 'deburr',
    status: 'done',
    machineId: 'mach-2',
    standardMinutes: 12,
    siloId: 'silo-finish',
    silo: 'Finishing',
    ownerId: 'emp-2',
    stationCode: 'ST-FIN-A',
    dailyKpiTarget: { targetUnitsPerShift: 200, maxDefectRatePercent: 2, targetCycleMinutes: 11 },
  },
  {
    id: 'op-3',
    productId: 'prod-1',
    sequence: 3,
    name: 'Assembly',
    stepCode: 'assemble',
    status: 'in_progress',
    machineId: 'mach-3',
    standardMinutes: 35,
    siloId: 'silo-assembly',
    silo: 'Assembly',
    ownerId: 'emp-1',
    stationCode: 'ST-ASSY-03',
    dailyKpiTarget: { targetUnitsPerShift: 100, maxDefectRatePercent: 2.5, targetCycleMinutes: 34 },
  },
  {
    id: 'op-4',
    productId: 'prod-1',
    sequence: 4,
    name: 'Functional test',
    stepCode: 'test',
    status: 'queued',
    standardMinutes: 20,
    siloId: 'silo-test',
    silo: 'Test',
    ownerId: 'emp-2',
    stationCode: 'ST-TEST-01',
    dailyKpiTarget: { targetUnitsPerShift: 140, maxDefectRatePercent: 1, targetCycleMinutes: 19 },
  },
  {
    id: 'op-5',
    productId: 'prod-2',
    sequence: 1,
    name: 'SMT place',
    stepCode: 'smt',
    status: 'done',
    machineId: 'mach-4',
    standardMinutes: 55,
    siloId: 'silo-smt',
    silo: 'SMT',
    ownerId: 'emp-1',
    stationCode: 'ST-SMT-01',
    dailyKpiTarget: { targetUnitsPerShift: 80, maxDefectRatePercent: 2, targetCycleMinutes: 54 },
  },
  {
    id: 'op-6',
    productId: 'prod-2',
    sequence: 2,
    name: 'AOI',
    stepCode: 'aoi',
    status: 'in_progress',
    machineId: 'mach-4',
    standardMinutes: 18,
    siloId: 'silo-smt',
    silo: 'SMT',
    ownerId: 'emp-2',
    stationCode: 'ST-AOI-01',
    dailyKpiTarget: { targetUnitsPerShift: 220, maxDefectRatePercent: 1.5, targetCycleMinutes: 17 },
  },
]
