/** @type {import('./model.js').Operation[]} */
export const operations = [
  {
    id: 'op-1',
    productId: 'prod-1',
    sequence: 1,
    name: 'Tube cutting',
    stepCode: 'cut',
    status: 'done',
    machineId: 'mach-1',
    standardMinutes: 48,
    siloId: 'silo-cutting',
    silo: 'Cutting cell',
    ownerId: 'emp-1',
    stationCode: 'ST-CUT-01',
    dailyKpiTarget: { targetUnitsPerShift: 96, maxDefectRatePercent: 1.5, targetCycleMinutes: 47 },
  },
  {
    id: 'op-2',
    productId: 'prod-1',
    sequence: 2,
    name: 'Weld mounting plate',
    stepCode: 'weld',
    status: 'done',
    machineId: 'mach-2',
    standardMinutes: 12,
    siloId: 'silo-welding',
    silo: 'Welding',
    ownerId: 'emp-2',
    stationCode: 'ST-WELD-A',
    dailyKpiTarget: { targetUnitsPerShift: 200, maxDefectRatePercent: 2, targetCycleMinutes: 11 },
  },
  {
    id: 'op-3',
    productId: 'prod-1',
    sequence: 3,
    name: 'Powder coating',
    stepCode: 'coat',
    status: 'in_progress',
    machineId: 'mach-3',
    standardMinutes: 35,
    siloId: 'silo-coating',
    silo: 'Powder coating',
    ownerId: 'emp-1',
    stationCode: 'ST-COAT-03',
    dailyKpiTarget: { targetUnitsPerShift: 100, maxDefectRatePercent: 2.5, targetCycleMinutes: 34 },
  },
  {
    id: 'op-4',
    productId: 'prod-1',
    sequence: 4,
    name: 'Final inspection & pack',
    stepCode: 'pack',
    status: 'queued',
    standardMinutes: 20,
    siloId: 'silo-pack',
    silo: 'Inspection & packing',
    ownerId: 'emp-2',
    stationCode: 'ST-PACK-01',
    dailyKpiTarget: { targetUnitsPerShift: 140, maxDefectRatePercent: 1, targetCycleMinutes: 19 },
  },
  {
    id: 'op-5',
    productId: 'prod-2',
    sequence: 1,
    name: 'Press & bend',
    stepCode: 'press',
    status: 'done',
    machineId: 'mach-4',
    standardMinutes: 55,
    siloId: 'silo-press',
    silo: 'Press shop',
    ownerId: 'emp-1',
    stationCode: 'ST-PRESS-01',
    dailyKpiTarget: { targetUnitsPerShift: 80, maxDefectRatePercent: 2, targetCycleMinutes: 54 },
  },
  {
    id: 'op-6',
    productId: 'prod-2',
    sequence: 2,
    name: 'Weld seam inspection',
    stepCode: 'seam_check',
    status: 'in_progress',
    machineId: 'mach-4',
    standardMinutes: 18,
    siloId: 'silo-press',
    silo: 'Press shop',
    ownerId: 'emp-2',
    stationCode: 'ST-SEAM-01',
    dailyKpiTarget: { targetUnitsPerShift: 220, maxDefectRatePercent: 1.5, targetCycleMinutes: 17 },
  },
]
