/** @type {import('./model.js').Machine[]} */
export const machines = [
  {
    id: 'mach-1',
    name: 'Mill 01',
    workCenterCode: 'WC-MILL',
    status: 'running',
    capabilities: ['3-axis milling', 'aluminum', 'titanium light'],
    hourlyRate: 142,
    utilization: 78,
    maintenanceHistory: [
      { date: '2026-01-12', description: 'Spindle bearing check' },
      { date: '2025-10-03', description: 'Annual calibration' },
    ],
    downtimeHours: 12,
    qualityRisk: 'low',
    notes: 'Primary housing cell; pair with deburr bench.',
  },
  {
    id: 'mach-2',
    name: 'Deburr bench A',
    workCenterCode: 'WC-FIN',
    status: 'idle',
    capabilities: ['manual finish', 'inspection staging'],
    hourlyRate: 68,
    utilization: 42,
    maintenanceHistory: [{ date: '2026-02-20', description: 'Dust extraction service' }],
    downtimeHours: 4,
    qualityRisk: 'medium',
    notes: 'Shared across prod-1 and prod-2 finishing.',
  },
  {
    id: 'mach-3',
    name: 'Assy station 3',
    workCenterCode: 'WC-ASSY',
    status: 'running',
    capabilities: ['mechanical assembly', 'torque logging'],
    hourlyRate: 95,
    utilization: 71,
    maintenanceHistory: [{ date: '2025-12-18', description: 'Fixture swap program' }],
    downtimeHours: 8,
    qualityRisk: 'low',
    notes: 'Supports control module builds.',
  },
  {
    id: 'mach-4',
    name: 'SMT line 1',
    workCenterCode: 'WC-SMT',
    status: 'down',
    capabilities: ['SMT placement', 'reflow'],
    hourlyRate: 210,
    utilization: 0,
    maintenanceHistory: [{ date: '2026-04-09', description: 'Conveyor motor replacement' }],
    downtimeHours: 36,
    qualityRisk: 'high',
    notes: 'Down for motor; ETA return next week.',
  },
]
