/** @type {import('./model.js').Machine[]} */
export const machines = [
  {
    id: 'mach-1',
    name: 'Tube saw 01',
    workCenterCode: 'WC-CUT',
    status: 'running',
    capabilities: ['tube cutting', 'steel', 'aluminium light'],
    hourlyRate: 142,
    utilization: 78,
    maintenanceHistory: [
      { date: '2026-01-12', description: 'Blade & feed roller check' },
      { date: '2025-10-03', description: 'Annual calibration' },
    ],
    downtimeHours: 12,
    qualityRisk: 'low',
    notes: 'Primary leg cell; feeds the welding stations.',
  },
  {
    id: 'mach-2',
    name: 'Weld cell A',
    workCenterCode: 'WC-WELD',
    status: 'idle',
    capabilities: ['MIG welding', 'jig fixturing'],
    hourlyRate: 68,
    utilization: 42,
    maintenanceHistory: [{ date: '2026-02-20', description: 'Fume extraction service' }],
    downtimeHours: 4,
    qualityRisk: 'medium',
    notes: 'Shared across ADILS and LERBERG weldments.',
  },
  {
    id: 'mach-3',
    name: 'Powder line 1',
    workCenterCode: 'WC-COAT',
    status: 'running',
    capabilities: ['powder coating', 'curing oven'],
    hourlyRate: 95,
    utilization: 71,
    maintenanceHistory: [{ date: '2025-12-18', description: 'Spray gun nozzle swap' }],
    downtimeHours: 8,
    qualityRisk: 'low',
    notes: 'RAL 9016 white and grey runs; colour change ~40 min.',
  },
  {
    id: 'mach-4',
    name: 'Press brake 01',
    workCenterCode: 'WC-PRESS',
    status: 'down',
    capabilities: ['CNC bending', 'sheet stamping'],
    hourlyRate: 210,
    utilization: 0,
    maintenanceHistory: [{ date: '2026-04-09', description: 'Hydraulic pump replacement' }],
    downtimeHours: 36,
    qualityRisk: 'high',
    notes: 'Down for pump; ETA return next week.',
  },
]
