/** @type {import('./model.js').Inquiry[]} */
export const inquiries = [
  {
    id: 'inq-seed-1',
    productId: 'prod-1',
    customerId: 'client-1',
    receivedAt: '2026-04-01T08:10:00.000Z',
    channel: 'email',
    status: 'feasibility_done',
    summary: 'ADILS steel table leg — follow-up volume call-off',
    requestedQuantity: 500,
    requestedDeadline: '2026-07-30',
    specificationNote: 'Powder coat RAL 9016 white; length tolerance ±0.5 mm; weld spatter-free per IOS-MAT.',
    customerContactName: 'Ingrid Lund',
    customerContactEmail: 'ingrid.lund@ikea.com',
    missingFields: [],
    attachments: [
      { id: 'att-1', name: 'adils-leg-revC.pdf', kind: 'drawing' },
      { id: 'att-2', name: 'powder-coat-spec.docx', kind: 'spec' },
    ],
    feasibilityResult: 'feasible',
    feasibilityNote: 'Existing weld jigs reusable; powder line capacity available in Q2.',
  },
  {
    id: 'inq-seed-2',
    productId: 'prod-2',
    customerId: 'client-2',
    receivedAt: '2026-04-22T14:45:00.000Z',
    channel: 'portal',
    status: 'intake_pending',
    summary: 'LERBERG side frame — additional batch request',
    requestedQuantity: 200,
    requestedDeadline: '2026-06-15',
    customerContactName: 'Klaus Werner',
    customerContactEmail: 'klaus.werner@ikea.com',
    missingFields: ['drawings', 'specifications'],
    attachments: [],
  },
]
