/** @type {import('./model.js').Inquiry[]} */
export const inquiries = [
  {
    id: 'inq-seed-1',
    productId: 'prod-1',
    customerId: 'client-1',
    receivedAt: '2026-04-01T08:10:00.000Z',
    channel: 'email',
    status: 'feasibility_done',
    summary: 'Precision aluminum housing — follow-up volume order',
    requestedQuantity: 500,
    requestedDeadline: '2026-07-30',
    specificationNote: 'Anodized finish, tolerance ±0.05mm on bore.',
    customerContactName: 'Ingrid Lund',
    customerContactEmail: 'ingrid.lund@example.com',
    missingFields: [],
    attachments: [
      { id: 'att-1', name: 'housing-drawing-revC.pdf', kind: 'drawing' },
      { id: 'att-2', name: 'surface-spec.docx', kind: 'spec' },
    ],
    feasibilityResult: 'feasible',
    feasibilityNote: 'Existing tooling reusable; capacity available in Q2.',
  },
  {
    id: 'inq-seed-2',
    productId: 'prod-2',
    customerId: 'client-2',
    receivedAt: '2026-04-22T14:45:00.000Z',
    channel: 'portal',
    status: 'intake_pending',
    summary: 'Control module — additional batch request',
    requestedQuantity: 200,
    requestedDeadline: '2026-06-15',
    customerContactName: 'Klaus Werner',
    customerContactEmail: 'klaus.werner@example.com',
    missingFields: ['drawings', 'specifications'],
    attachments: [],
  },
]
