/** @type {import('./model.js').Task[]} */
export const tasks = [
  {
    id: 'task-1',
    taskKey: 'bom-housing-q2',
    title: 'Finalize BOM for housing',
    assigneeId: 'emp-1',
    productId: 'prod-1',
    dueDate: '2026-04-20',
    status: 'in_progress',
    priority: 'high',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'design',
    workstream: 'planning',
    quoteId: 'quote-1',
  },
  {
    id: 'task-2',
    taskKey: 'fixture-cal-q1',
    title: 'Fixture calibration',
    assigneeId: 'emp-2',
    productId: 'prod-1',
    dueDate: '2026-03-01',
    status: 'draft',
    priority: 'medium',
    plannedYear: 2026,
    plannedQuarter: 'Q1',
    phaseId: 'prototype',
    workstream: 'manufacturing',
  },
  {
    id: 'task-3',
    taskKey: 'iqc-module-q2',
    title: 'IQC sampling plan',
    assigneeId: 'emp-1',
    productId: 'prod-2',
    dueDate: '2026-04-15',
    status: 'blocked',
    priority: 'high',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'quality',
    workstream: 'quality',
  },
  {
    id: 'task-4',
    taskKey: 'archive-docs-q4',
    title: 'Archive documentation',
    assigneeId: 'emp-3',
    productId: 'prod-3',
    dueDate: '2025-12-01',
    status: 'resolved',
    priority: 'low',
    completedAt: '2025-11-28',
    plannedYear: 2025,
    plannedQuarter: 'Q4',
    phaseId: 'released',
    workstream: 'planning',
  },
  {
    id: 'task-5',
    taskKey: 'quote-tech-review-prod-1',
    title: 'Quotation technical review (VSM 1.4)',
    assigneeId: 'emp-1',
    productId: 'prod-1',
    dueDate: '2026-04-12',
    status: 'resolved',
    priority: 'high',
    completedAt: '2026-04-11',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'concept',
    workstream: 'quotation',
    quoteId: 'quote-1',
  },
  {
    id: 'task-6',
    taskKey: 'quote-costing-prod-1',
    title: 'Quotation costing rollup',
    assigneeId: 'emp-2',
    productId: 'prod-1',
    dueDate: '2026-04-14',
    status: 'draft',
    priority: 'high',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'concept',
    workstream: 'quotation',
    quoteId: 'quote-1',
  },
  {
    id: 'task-7',
    taskKey: 'ship-prep-prod2',
    title: 'Shipping prep checklist',
    assigneeId: 'emp-3',
    productId: 'prod-2',
    dueDate: '2026-05-01',
    status: 'draft',
    priority: 'medium',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'quality',
    workstream: 'shipping',
    orderId: 'ord-2',
  },
  {
    id: 'task-8',
    taskKey: 'carryover-q1-machining',
    title: 'Rough machining — carryover',
    assigneeId: 'emp-2',
    productId: 'prod-1',
    dueDate: '2026-02-15',
    status: 'in_progress',
    priority: 'high',
    plannedYear: 2026,
    plannedQuarter: 'Q1',
    phaseId: 'production',
    workstream: 'manufacturing',
  },
  {
    id: 'task-shop-exec-1',
    taskKey: 'shop-floor-assembly-2026-04-11',
    title: 'Shop floor: Assembly',
    assigneeId: 'emp-2',
    productId: 'prod-1',
    dueDate: '2026-04-11',
    status: 'resolved',
    completedAt: '2026-04-11',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'production',
    workstream: 'manufacturing',
    operationId: 'op-3',
    assignmentDate: '2026-04-11',
    actualStart: '2026-04-11T06:30:00',
    actualEnd: '2026-04-11T13:45:00',
    actualGoodQty: 88,
    actualScrapQty: 2,
    actualDurationMinutes: 420,
    actualDowntimeMinutes: 25,
    actualDowntimeReason: 'Material wait',
    actualMachineId: 'mach-3',
    executionNote: 'First article OK',
  },
  {
    id: 'task-shop-owner-1',
    taskKey: 'shop-oversight-assembly-2026-04-11',
    title: 'Oversight: Assembly (2026-04-11)',
    assigneeId: 'emp-1',
    productId: 'prod-1',
    dueDate: '2026-04-11',
    status: 'draft',
    plannedYear: 2026,
    plannedQuarter: 'Q2',
    phaseId: 'production',
    workstream: 'manufacturing',
    operationId: 'op-3',
    assignmentDate: '2026-04-11',
  },
]
