/** @type {import('./model.js').QuoteDraft[]} */
export const quoteDrafts = [
  {
    id: 'quote-1',
    clientId: 'client-1',
    productId: 'prod-1',
    inquiryId: 'inq-seed-1',
    status: 'draft',
    subtotal: 7300,
    marginPercent: 18,
    updatedAt: '2026-05-10',
    currency: 'EUR',
    language: 'en',
    unitPrice: 61.2,
    leadTimeDays: 40,
    validUntil: '2026-06-30',
    currentVersionNo: 1,
    currentVersionId: 'qv-1-1',
  },
  {
    id: 'quote-2',
    clientId: 'client-2',
    productId: 'prod-2',
    status: 'pending_approval',
    subtotal: 11200,
    marginPercent: 22,
    updatedAt: '2026-05-12',
    currency: 'EUR',
    language: 'en',
    unitPrice: 140,
    leadTimeDays: 28,
    validUntil: '2026-06-15',
    currentVersionNo: 1,
    currentVersionId: 'qv-2-1',
  },
  {
    id: 'quote-3',
    clientId: 'client-1',
    productId: 'prod-pkg-1',
    status: 'sent',
    subtotal: 4850,
    marginPercent: 15,
    updatedAt: '2026-05-05',
    currency: 'EUR',
    language: 'en',
    unitPrice: 97,
    leadTimeDays: 21,
    validUntil: '2026-05-26',
    currentVersionNo: 2,
    currentVersionId: 'qv-3-2',
  },
  {
    id: 'quote-4',
    clientId: 'client-2',
    productId: 'prod-1',
    status: 'revision_requested',
    subtotal: 9100,
    marginPercent: 17,
    updatedAt: '2026-04-28',
    currency: 'EUR',
    language: 'bg',
    unitPrice: 91,
    leadTimeDays: 35,
    validUntil: '2026-05-31',
    currentVersionNo: 1,
    currentVersionId: 'qv-4-1',
  },
  {
    id: 'quote-hist-1',
    clientId: 'client-1',
    productId: 'prod-1',
    status: 'accepted',
    subtotal: 6564,
    marginPercent: 16,
    updatedAt: '2025-11-01',
    currency: 'EUR',
    language: 'en',
    unitPrice: 54.7,
    leadTimeDays: 45,
    validUntil: '2025-12-15',
  },
  {
    id: 'quote-hist-2',
    clientId: 'client-2',
    productId: 'prod-2',
    status: 'accepted',
    subtotal: 8960,
    marginPercent: 20,
    updatedAt: '2026-02-15',
    currency: 'EUR',
    language: 'en',
    unitPrice: 112,
    leadTimeDays: 30,
    validUntil: '2026-03-31',
  },
  {
    id: 'quote-hist-3',
    clientId: 'client-1',
    productId: 'prod-rm-1',
    status: 'rejected',
    subtotal: 3200,
    marginPercent: 12,
    updatedAt: '2026-03-10',
    currency: 'EUR',
    language: 'en',
    unitPrice: 32,
    leadTimeDays: 14,
    validUntil: '2026-04-10',
  },
]

/** @type {import('./model.js').QuoteVersion[]} */
export const quoteVersions = [
  {
    id: 'qv-1-1',
    quoteId: 'quote-1',
    versionNo: 1,
    status: 'draft',
    createdAt: '2026-05-08T12:00:00.000Z',
    subtotal: 7300,
    marginPercent: 18,
    currency: 'EUR',
    language: 'en',
    unitPrice: 61.2,
    leadTimeDays: 40,
    validUntil: '2026-06-30',
    deliveryTerms: 'FCA Plovdiv (Incoterms 2020)',
    paymentTerms: '30 days net',
    moq: 100,
  },
  {
    id: 'qv-2-1',
    quoteId: 'quote-2',
    versionNo: 1,
    status: 'approved',
    createdAt: '2026-05-10T09:00:00.000Z',
    subtotal: 11200,
    marginPercent: 22,
    currency: 'EUR',
    language: 'en',
    unitPrice: 140,
    leadTimeDays: 28,
    validUntil: '2026-06-15',
    deliveryTerms: 'DAP Customer site',
    paymentTerms: '50% advance, 50% on delivery',
    moq: 80,
  },
  {
    id: 'qv-3-1',
    quoteId: 'quote-3',
    versionNo: 1,
    status: 'superseded',
    createdAt: '2026-04-20T10:00:00.000Z',
    subtotal: 5200,
    marginPercent: 14,
    currency: 'EUR',
    language: 'en',
    unitPrice: 104,
    leadTimeDays: 25,
    validUntil: '2026-05-20',
    deliveryTerms: 'EXW Plovdiv',
    paymentTerms: '30 days net',
  },
  {
    id: 'qv-3-2',
    quoteId: 'quote-3',
    versionNo: 2,
    status: 'sent',
    createdAt: '2026-05-03T14:00:00.000Z',
    sentAt: '2026-05-05T08:30:00.000Z',
    subtotal: 4850,
    marginPercent: 15,
    currency: 'EUR',
    language: 'en',
    unitPrice: 97,
    leadTimeDays: 21,
    validUntil: '2026-05-26',
    deliveryTerms: 'FCA Plovdiv (Incoterms 2020)',
    paymentTerms: '30 days net',
    moq: 50,
    supersedesVersionId: 'qv-3-1',
  },
  {
    id: 'qv-4-1',
    quoteId: 'quote-4',
    versionNo: 1,
    status: 'decided',
    createdAt: '2026-04-22T11:00:00.000Z',
    sentAt: '2026-04-25T09:00:00.000Z',
    subtotal: 9100,
    marginPercent: 17,
    currency: 'EUR',
    language: 'bg',
    unitPrice: 91,
    leadTimeDays: 35,
    validUntil: '2026-05-31',
    deliveryTerms: 'FCA Пловдив (Incoterms 2020)',
    paymentTerms: '30 дни нето',
    moq: 100,
  },
]

/** @type {import('./model.js').QuoteLineItem[]} */
export const quoteLineItems = [
  {
    id: 'qli-1-1-1',
    quoteVersionId: 'qv-1-1',
    kind: 'material',
    description: 'Aluminum billet 6061-T6',
    quantity: 500,
    unitPrice: 4.2,
    totalPrice: 2100,
  },
  {
    id: 'qli-1-1-2',
    quoteVersionId: 'qv-1-1',
    kind: 'labor',
    description: 'CNC machining, 0.18 h/unit',
    quantity: 500,
    unitPrice: 9.5,
    totalPrice: 4750,
  },
  {
    id: 'qli-1-1-3',
    quoteVersionId: 'qv-1-1',
    kind: 'tooling',
    description: 'Fixture refresh (amortized)',
    quantity: 1,
    unitPrice: 450,
    totalPrice: 450,
  },
]

/** @type {import('./model.js').QuoteApproval[]} */
export const quoteApprovals = [
  {
    id: 'qa-seed-1',
    quoteVersionId: 'qv-2-1',
    approverEmployeeId: 'emp-1',
    decision: 'approved',
    decidedAt: '2026-05-11T10:00:00.000Z',
    note: 'Margin and lead time are acceptable.',
  },
]

/** @type {import('./model.js').QuoteDocument[]} */
export const quoteDocuments = [
  {
    id: 'qdoc-seed-1',
    quoteVersionId: 'qv-1-1',
    kind: 'drawing',
    name: 'Housing_rev3.pdf',
    storageRef: 'mock://drawings/housing-rev3.pdf',
    createdAt: '2026-05-09T08:00:00.000Z',
  },
]

/** @type {import('./model.js').QuoteDecision[]} */
export const quoteDecisions = [
  {
    id: 'qd-seed-1',
    quoteVersionId: 'qv-4-1',
    decision: 'revision_requested',
    decidedAt: '2026-04-28T15:30:00.000Z',
    customerContactName: 'Maria Ivanova',
    customerContactEmail: 'maria@client2.bg',
    comment: 'Please reduce lead time to 25 days and provide a volume discount for 200+ units.',
    token: 'tok-seed-qv-4-1',
  },
]
